[tools]

act = "latest"
awscli = 'latest'
bun = "latest"
deno = 'latest'
gcloud = "latest"
go = 'latest'
kustomize = 'latest'
nodejs = 'lts'
ollama = "latest"
python = 'latest'
ruby = 'latest'
rust = 'latest'
stern = "latest"
terraform = 'latest'
usage = "latest"
uv = "latest"
pnpm = "latest"

"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:difit" = "latest"
"npm:zenn-cli" = "latest"

"aqua:mame/wsl2-ssh-agent" = "latest"
chezmoi = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
